.TH capmarker 1 "01 Feb 2012" "BTH" "Measurement Area Manual"
.SH NAME
capmarker \- Send a special packet that be identified in the capture stream.
.SH SYNOPSIS
.nf
.B capmarker \-e \fIEXP\fP \-r \fIRUN\fP [\-k \fIKEY\fP] [\-s \fISEQ\fP]
.SH DESCRIPTION

.TP
\fB\-h\fR, \fB\-\-help
Short help.
.SH COPYRIGHT
Copyright (C) 2011-2012 David Sveningsson <dsv@bth.se>.
.SH "SEE ALSO"
stream-address(3), capplay(1)
