language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libpcap-dev
      - libssl-dev
      - libcppunit-dev

before_script:
  - autoreconf -si

script:
  - ./configure
  - make
  - make check
